CATALOGUE_HOST: catalogue.mannamsarath.online
USER_HOST: user.mannamsarath.online
SHIPPING_HOST: shipping.mannamsarath.online
CART_HOST: cart.mannamsarath.online
PAYMENT_HOST: payment.mannamsarath.online
